app:
    resource: "@App/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 

# API REST 
# rest : 
#   type : rest 
#   resource : "routing_rest.yml"
#   prefix : /api