app:
    resource: "@App/Controller/"
    type:     annotation

# USER ROUTING
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

# FOS USER ROUTING
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 

